services:
  identitydb:
    image: postgres:17.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: identityuser
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@domain.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD} 
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  seq:
    image: datalust/seq
    restart: always
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_DEFAULT_PASSWORD}
    volumes:
      - seq_data:/data

volumes:
  local_pgdata:
  pgadmin-data:
  seq_data: