name: IdentityAPI-Deploy

on:
  push:
    paths:
      - .github/workflows/**

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Migrate database
    runs-on: tikal-azure-runner
    strategy:
      matrix:
        dotnet-version: ["9.0.X"]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: './IdentityAPI/packages.lock.json'
    
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef
    
      - name: Restore IdentityAPI
        run: dotnet restore ./IdentityAPI/IdentityAPI.csproj --locked-mode

      - name: Build IdentityAPI
        run: dotnet build ./IdentityAPI/IdentityAPI.csproj --configuration Release --no-restore

      - name: Create bundle
        run: |
          cd ./IdentityAPI
          dotnet ef migrations bundle --project ./IdentityAPI.csproj --output bundle

      - name: Apply migration
        run: |
          cd ./IdentityAPI
          ./efbundle --connection "${{ secrets.IDENTITY_DB_CONNECTION_STRING }}"
