name: IdentityAPI-Deploy

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  test:
    name: workflow test
    runs-on: tikal-azure-runner
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4